### ISSUE TITLE
Passwords with URL aren't displayed

### ISSUE THREAD

**Issue by robsalasco** [karsai5/KeePass-Alfred-Workflow#2]
Hi! I have entries with added urls and that causes a bug in the workflow not showing the title and the username.

Hope can you fix the code!

**Comment by karsai5** [comment]
Good catch on the bug! I did this over a weekend and couldn't work out why some items wont showing. I use lastpass now just because of the chrome extensions, so sorry it took so long for me to come back and fix this bug. It seemed to be an issue with kpli, the underlying program for accessing keepass databases. Should be fixed now as of commit https://github.com/karsai5/KeePass-Alfred-Workflow/commit/c3191dfc5f15f5a649aaebc07c5ef0dd69d669e1. You can download the new workflow at https://github.com/karsai5/KeePass-Alfred-Workflow/releases/tag/1.4
