### ISSUE TITLE
Import fails for pexpect

### ISSUE THREAD

**Issue by snwflake** [karsai5/KeePass-Alfred-Workflow#3]
Code 1: Traceback (most recent call last):
```
File "/Users/snwFlake/Documents/alfred_sync/Alfred.alfredpreferences/workflows/user.workflow.00ED48BF-4BFE-4922-9620-4DC5386BB643/search.py", 
line 7, in <module>
   import pexpect
ImportError: No module named pexpect
```

**Comment by karsai5** [comment]
I've added in pexpect into the package so that it doesn't need to be installed globally on your system. Fixed in https://github.com/karsai5/KeePass-Alfred-Workflow/commit/5692de07682f48fed98a5111df85776838c52c87. You can download the updated package at https://github.com/karsai5/KeePass-Alfred-Workflow/releases/tag/1.4

Let me know if you're still having issues!

**Comment by snwflake** [comment]
Going to test it, although I wrote my own workflow, w/ improved security.
